### Dataset Loading or Definition

In [28]:
#Toy Dataset of names
names = ["Rajkamal", "Rajendra", "Kamal", "Chetan", "Rohinee","Ansh", "Dipak", "Pratik", "Arnav", "Komal"]
print(names)
#Toy Dataset of alien language
alien_language = "My name is anthongy gonzalvez, mai duniya mai akela hu!"
print(alien_language)

['Rajkamal', 'Rajendra', 'Kamal', 'Chetan', 'Rohinee', 'Ansh', 'Dipak', 'Pratik', 'Arnav', 'Komal']
My name is anthongy gonzalvez, mai duniya mai akela hu!


### Vocabulary + ctoi + itoc Creation

In [29]:
names = [name.lower() for name in names]
vocab_names = sorted(list(set(''.join(names))))
print("Vocab of names: ",vocab_names)
#I am taking start and end symbol to be '$' - it will serve as input for first character as output, so it is necessary ath the start
#and at the end also it is necessary because we want to signify end of the name
ctoi_names = {}
ctoi_names = {ch:idx+1 for idx,ch in enumerate(vocab_names)}#gives us token ids and helps in encoding
ctoi_names['$'] = 0
print("ctoi of names: ",ctoi_names)
itoc_names = {}
itoc_names = {idx+1:ch for idx,ch in enumerate(vocab_names)}#gives us token ids and helps in encoding
itoc_names[0] = '$'
print("itos of names: ", itoc_names)

#We will assume the alien language to have 
alien_language = alien_language.lower()
vocab_alien_lang = sorted(list(set(alien_language)))
print("Vocab of alien language: ", vocab_alien_lang)
ctoi_alien_lang = {}
ctoi_alien_lang = {ch:idx+1 for idx,ch in enumerate(vocab_alien_lang)}#gives us token ids and helps in encoding
ctoi_alien_lang['$'] = 0
print("ctoi of alien language", ctoi_alien_lang)
itoc_alien_lang = {idx+1:ch for idx,ch in enumerate(vocab_alien_lang)}#gives us dekoded tokens from token ids and hence, helps in decoding
itoc_alien_lang[0] = '$'
print("itoc of alien language", itoc_alien_lang)

Vocab of names:  ['a', 'c', 'd', 'e', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'v']
ctoi of names:  {'a': 1, 'c': 2, 'd': 3, 'e': 4, 'h': 5, 'i': 6, 'j': 7, 'k': 8, 'l': 9, 'm': 10, 'n': 11, 'o': 12, 'p': 13, 'r': 14, 's': 15, 't': 16, 'v': 17, '$': 0}
itos of names:  {1: 'a', 2: 'c', 3: 'd', 4: 'e', 5: 'h', 6: 'i', 7: 'j', 8: 'k', 9: 'l', 10: 'm', 11: 'n', 12: 'o', 13: 'p', 14: 'r', 15: 's', 16: 't', 17: 'v', 0: '$'}
Vocab of alien language:  [' ', '!', ',', 'a', 'd', 'e', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 's', 't', 'u', 'v', 'y', 'z']
ctoi of alien language {' ': 1, '!': 2, ',': 3, 'a': 4, 'd': 5, 'e': 6, 'g': 7, 'h': 8, 'i': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 's': 15, 't': 16, 'u': 17, 'v': 18, 'y': 19, 'z': 20, '$': 0}
itoc of alien language {1: ' ', 2: '!', 3: ',', 4: 'a', 5: 'd', 6: 'e', 7: 'g', 8: 'h', 9: 'i', 10: 'k', 11: 'l', 12: 'm', 13: 'n', 14: 'o', 15: 's', 16: 't', 17: 'u', 18: 'v', 19: 'y', 20: 'z', 0: '$'}


### Simple Bigram Character-level language model
* Get counts matrix/tensor with dimension vocab*vocab
* Convert it into Probability matrix/tensor by dividing by row sum to each row element - row-wise
* Use this Probability matrix/tensor for prediction and stuff(computing the negative log likelihood)

In [53]:
#Build Bigram Character-level language model for names

N = torch.zeros((len(vocab_names)+1 , len(vocab_names)+1))
print(N.shape)

for w in names:
    char_list_w = ['$'] + list(w) + ['$']
    for ch1, ch2 in zip(char_list_w, char_list_w[1:]):
        ix1 = ctoi_names[ch1]
        ix2 = ctoi_names[ch2]
        N[ix1, ix2] += 1

print(N[:5])
print(N.shape)

P = N+1
P /= P.sum(dim=1, keepdims=True)

torch.Size([18, 18])
tensor([[0., 2., 1., 1., 0., 0., 0., 0., 2., 0., 0., 0., 0., 1., 3., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 2., 1., 3., 2., 2., 0., 0., 1., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.]])
torch.Size([18, 18])


In [56]:
#Sampling using the distributions captured by P

for i in range(5):

    out = []
    ix = 0
    while True:
        p = P[ix]
        ix = torch.multinomial(p, num_samples=1, replacement=True).item()
        out.append(itoc_names[ix])
        if ix == 0:
            break
    print(''.join(out))

ddjijajrnnhvdjejasrndimtrpiatmvcrrtlhsikhnasljcsekntojavvmmhictraiekvlolsamsh$
edcvptesthjrslhvrdh$
tppcmmapanar$
$
dskatjk$


In [58]:
#Computing the goodness of this model based on P - using the log likelihood of the predictions

log_likelihood = 0.0
n = 0 #Total samples, so that at last we can get average of log likelihood

for w in names:
    char_list_w = ['$'] + list(w) + ['$']
    for ch1, ch2 in zip(char_list_w, char_list_w[1:]):
        ix1 = ctoi_names[ch1]
        ix2 = ctoi_names[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1

print("Log likelihood: ", log_likelihood)
nll = -log_likelihood
print("nll: ",nll)
print("Average negative log likelihood: ", nll/n)

Log likelihood:  tensor(-154.4681)
nll:  tensor(154.4681)
Average negative log likelihood:  tensor(2.2387)


In [60]:
#Build Simple Bigram character-level language model

N_ = torch.zeros(((len(vocab_alien_lang)+1, len(vocab_alien_lang)+1)))

block_size = 1

context = [0] * block_size
char_word_list = ['$'] + list(alien_language) + ['$']
for ch1, ch2 in zip(char_word_list, char_word_list[1:]):
    ix1 = ctoi_alien_lang[ch1]
    ix2 = ctoi_alien_lang[ch2]
    N_[ix1,ix2] += 1

N_.shape

torch.Size([21, 21])

In [63]:
#Sampling from this model

P_ = N_+1
P_ /= P_/P_.sum(dim=1, keepdims=True)

for i in range(5):
    out = []
    ix = 0
    while True:
        p = P_[ix]
        ix = torch.multinomial(p, num_samples=1, replacement=True).item()
        out.append(itoc_alien_lang[ix])
        if ix == 0:
            break
    print(''.join(out))

iegtg!hhh,dgadstnuun,mzz$
vgukd$
m  tlv,!sulyoozklnnv$
siyheiuy!!vluvhdv  d$
ineoetnels!$


In [65]:
log_likelihood = 0.0
n = 0

char_list_alien_lang = ['$'] + list(alien_language) + ['$']
for ch1, ch2 in zip(char_list_alien_lang, char_list_alien_lang[1:]):
    ix1 = ctoi_alien_lang[ch1]
    ix2 = ctoi_alien_lang[ch2]
    prob = P_[ix1, ix2]
    log_likelihood += torch.log(prob)
    n += 1

print(log_likelihood)
nll = -log_likelihood
print("NLL: ",nll)
print("Average negative loss likelihood: ", nll/n)

tensor(181.0132)
NLL:  tensor(-181.0132)
Average negative loss likelihood:  tensor(-3.2324)


Note: Dataset building means *having input and output component - in case of n-gram character-level lanugage models it is going to be (n-1) characters as input and nth character as output - this window will keep sliding till we reach the text's end*.
As, simple bigram language model don't have any concept of "training" as such since, it is simply based on the statistical modelling achieved by computing N and then, P - which is thenused as the beacon of character-level prediction. Hence, it doesn't need dataset creation, computaiton of N and P is enough. Above, we also have show how to use it for sampling as well as computed the log likelihood of all the samples here (of the gold distribution captured directly from the dataset.)

Now, we will implement same bigram model but with trainable parameter (W) which will start from random initializaiton and then learn to become P or better than P - to give us equivalent or even smaller negative average log likelihood! But, before that, let's build the training dataset for it!

### Dataset Building

In [32]:
#Building dataset for names - with respect to bigram language model

import torch

block_size = 1 #context length: how many characters do we take to predict the next one

def build_dataset(words):
    X, Y = [], []
    for w in words:
        context = [0] * block_size #Give context as $ character's token_id
        for ch in w + '$':
            ix = ctoi_names[ch]
            X.append(context)
            Y.append(ix)
            context = context[1:] + [ix]
        
    X = torch.tensor(X)
    Y = torch.tensor(Y)
    print(X.shape, Y.shape)
    return X,Y

#import random
#random.seed(42)

n1 = int(0.8 * len(names))
n2 = int(0.9 * len(names))

Xtr_names, Ytr_names = build_dataset(names[:n1])
Xdev_names, Ydev_names = build_dataset(names[n1:n2])
Xte_names, Yte_names = build_dataset(names[n2:])

torch.Size([57, 1]) torch.Size([57])
torch.Size([6, 1]) torch.Size([6])
torch.Size([6, 1]) torch.Size([6])


In [33]:
Xtr_names[:5], Ytr_names[:5]

(tensor([[ 0],
         [14],
         [ 1],
         [ 7],
         [ 8]]),
 tensor([14,  1,  7,  8,  1]))

In [44]:
len(''.join(names))

59

In [42]:
#Building dataset for alien language with respect to bigram language model

block_size = 1

def build_dataset2(text):
    X, Y = [], []
    context = [0] * block_size
    for ch in text + '$':
        ix = ctoi_alien_lang[ch]
        X.append(context)
        Y.append(ix)
        context = context[1:] + [ix]
    X = torch.tensor(X)
    Y = torch.tensor(Y)
    print(X.shape, Y.shape)
    return X,Y

n1 = int(0.8 * len(alien_language))
n2 = int(0.9 * len(alien_language))

Xtr_alien_lang, Ytr_alien_lang = build_dataset2(alien_language[:n1])
Xdev_alien_lang, Ydev_alien_lang = build_dataset2(alien_language[n1:n2])
Xte_alien_lang, Yte_alien_lang = build_dataset2(alien_language[n2:])

torch.Size([45, 1]) torch.Size([45])
torch.Size([6, 1]) torch.Size([6])
torch.Size([7, 1]) torch.Size([7])


In [43]:
len(alien_language)

55

### Using Neural Network to Learn Distribution of Characters

In [103]:
W_names = torch.randn((len(vocab_names)+1, len(vocab_names)+1), requires_grad = True) #requires_grad = True, since, it is a trainable parameter

In [111]:
epochs = 15
import torch.nn as nn

for i in range(epochs):
    print("Epoch: ", i, " started!")
    for j in range(Xtr.shape[0]):
        #forward pass
        #print(Xtr[j])
        #print(Xtr[j].nelement())
        xenc = nn.functional.one_hot(Xtr[j], num_classes=len(vocab_names)+1).float()
        logits = xenc @ W_names
        print(logits.shape)
        counts = logits.exp()
        print(counts)
        probs = counts/counts.sum(dim=1, keepdims=True)
        #print(probs.sum(dim=1, keepdims=True))
        #print(probs.shape)
        #print(probs)
        loss = -probs[torch.arange(Xtr[j].nelement()), Ytr[j]].log().mean() + 0.01*(W_names**2).mean()

        #print(loss.item())

        #backward pass
        W_names.grad = None
        loss.backward()

        #update
        W_names.data += -3 * W_names.grad
        break
    print(loss.item())
    break
        #break
    #break

Epoch:  0  started!
torch.Size([1, 18])
tensor([[  0.4639,  19.7803,  14.3185,  25.7107,   0.4684,   0.4596,   0.3184,
           0.4230,  12.4094,   0.3814,   0.4649,   0.3559,   0.4005, 185.6587,
          18.1433,   0.4399,   0.4318,   0.4260]], grad_fn=<ExpBackward0>)
2.771587371826172


In [115]:
W_alien_lang = torch.randn((len(vocab_alien_lang)+1, len(vocab_alien_lang)+1), requires_grad = True)

In [116]:
epochs = 15
for i in range(epochs):
    print("Epoch ",i," started!")
    for j in range(Xtr.shape[0]):
        #forward pass
        xenc = nn.functional.one_hot(Xtr[j], num_classes=len(vocab_alien_lang)+1).float()
        logits = xenc @ W_alien_lang
        #print(logits.shape)
        counts = logits.exp()
        #print(counts.shape)
        probs = counts/counts.sum(dim=1, keepdims=True)
        loss = -probs[torch.arange(Xtr[j].nelement()), Ytr[j]].log().mean() + 0.01 * (W_alien_lang**2).mean()
        #backward pass
        W_alien_lang.grad = None
        loss.backward()
        #Update W
        W_alien_lang.data += -3 * W_alien_lang.grad
        #break
    print(loss.item())
    #break
        
        

Epoch  0  started!
0.4019641876220703
Epoch  1  started!
0.19466714560985565
Epoch  2  started!
0.15605615079402924
Epoch  3  started!
0.1395486295223236
Epoch  4  started!
0.13049766421318054
Epoch  5  started!
0.12486027926206589
Epoch  6  started!
0.12106199562549591
Epoch  7  started!
0.11835967004299164
Epoch  8  started!
0.11635943502187729
Epoch  9  started!
0.11483220756053925
Epoch  10  started!
0.11363725364208221
Epoch  11  started!
0.11268284171819687
Epoch  12  started!
0.11190763115882874
Epoch  13  started!
0.11126876622438431
Epoch  14  started!
0.11073500663042068


### Sampling from neural network based bigram character-level language model

In [120]:
for i in range(5):
    out = []
    ix = 0
    while True:
        #forward pass
        xenc = nn.functional.one_hot(torch.tensor([ix]), num_classes = len(vocab_names)+1).float()
        logits = xenc @ W_names
        counts = logits.exp()
        #print(counts.shape)
        probs = counts/counts.sum(dim=1, keepdims=True)

        ix = torch.multinomial(probs, num_samples=1, replacement=True).item()
        out.append(itoc_names[ix])
        if ix == 0:
            break
    print(''.join(out))

ratikal$
ratik$
ratik$
ransh$
dik$


In [121]:
for i in range(5):
    out = []
    ix = 0
    while True:
        xenc = nn.functional.one_hot(torch.tensor([ix]), num_classes = len(vocab_alien_lang)+1).float()
        logits = xenc @ W_alien_lang
        counts = logits.exp()
        probs = counts/counts.sum(dim=1, keepdim=True)

        ix = torch.multinomial(probs, num_samples=1, replacement=True).item()
        out.append(itoc_alien_lang[ix])
        if ix == 0:
            break
    print(''.join(out))

 lsd$
!d$
,eh$
 teno $
no tlsd$


Currently, learning weight matrix seems simple, since it is just vocab_size * vocab_size. This is because block_size = 1.<br>
If we were to increase block_size to 2, then, (vocab_size * vocab_size) - all possible pairs of two character context * vocab_size(distribution of probs over vocabulary), so weight matrix's size will be (vocab_size**2, vocab_size)!<br>
So, as the block_size keeps increasing number of parameters are going to exponentially increase! Similarly, for the simple n-gram language model also, the size of N and P will exponentially grow to capture all context nuances - they will mostly be sparse!

So, this is a good solution for bigram or say at max trigram models, but for general n-gram models this become infeasible, this is where Bengio et al's MLP comes to our rescue!

### MLP for character-level n-gram language model

In [164]:
emb_dim = 10 #embedding dimensions
hidden_dim = 100
block_size = 1
C = torch.randn((len(vocab_names)+1, emb_dim), requires_grad = True)
W1 = torch.randn((emb_dim*block_size, hidden_dim), requires_grad = True)
b1 = torch.randn(hidden_dim, requires_grad = True)
W2 = torch.randn((hidden_dim, len(vocab_names)+1), requires_grad = True)
b2 = torch.randn(len(vocab_names)+1, requires_grad = True)

parameters = [C, W1, b1, W2, b2]

sum(p.nelement() for p in parameters)

3098

In [165]:
epochs = 100
for i in range(epochs):
    print("Epoch ",i," started!")
    for j in range(Xtr.shape[0]):
        emb = C[Xtr[j]]
        #print(emb.shape)
        h = torch.tanh(emb.view(-1, emb_dim*block_size) @ W1 + b1)
        #print(h.shape)
        logits = h @ W2 + b2
        #print(logits.shape)
        #counts = logits.exp()
        #probs = counts/counts.sum(1, keepdims=True)
        #loss = torch.tensor(torch.arange(Xtr[j]), Ytr[j])
        #print(logits.shape)
        #print(Ytr_names[j])
        #print(Ytr_names.shape)
        Ytr_names_one_hot = nn.functional.one_hot(Ytr_names[j], num_classes=len(vocab_names)+1).float()
        #print(Ytr_names_one_hot.shape)
        loss = nn.functional.cross_entropy(logits, Ytr_names_one_hot.view(-1, len(vocab_names)+1))

        for p in parameters:
            p.grad = None

        loss.backward()

        for p in parameters:
            p.data += -0.001 * p.grad
    print(loss.item())

Epoch  0  started!
27.830625534057617
Epoch  1  started!
26.544397354125977
Epoch  2  started!
25.539392471313477
Epoch  3  started!
24.680999755859375
Epoch  4  started!
23.83167266845703
Epoch  5  started!
22.983932495117188
Epoch  6  started!
22.155757904052734
Epoch  7  started!
21.356372833251953
Epoch  8  started!
20.591529846191406
Epoch  9  started!
19.865468978881836
Epoch  10  started!
19.179353713989258
Epoch  11  started!
18.533411026000977
Epoch  12  started!
17.92671775817871
Epoch  13  started!
17.356670379638672
Epoch  14  started!
16.819229125976562
Epoch  15  started!
16.308870315551758
Epoch  16  started!
15.819832801818848
Epoch  17  started!
15.34683895111084
Epoch  18  started!
14.885547637939453
Epoch  19  started!
14.432499885559082
Epoch  20  started!
13.984454154968262
Epoch  21  started!
13.537090301513672
Epoch  22  started!
13.084402084350586
Epoch  23  started!
12.62091064453125
Epoch  24  started!
12.145729064941406
Epoch  25  started!
11.662263870239258


I am propagating gradients with respect to loss of single sample rather than a batch or that of the whole samples, that's why such unstable training is seen in loss!!

In [166]:
emb_dim = 10
block_size = 1
C_ = torch.randn((len(vocab_alien_lang)+1, emb_dim), requires_grad = True)
W1_ = torch.randn((emb_dim * block_size, hidden_dim), requires_grad = True)
b1_ = torch.randn(hidden_dim, requires_grad = True)
W2_ = torch.randn((hidden_dim, len(vocab_alien_lang)+1), requires_grad = True)
b2_ = torch.randn(len(vocab_alien_lang)+1, requires_grad = True)

parameters = [C_, W1_, b1_, W2_, b2_]

sum(p.nelement() for p in parameters)

3431

In [170]:
epochs = 10

for i in range(epochs):
    print("Epoch ",i, " has started")
    for j in range(Xtr.shape[0]):
        emb = C_[Xtr[j]]
        h = torch.tanh(emb.view(-1, emb_dim * block_size) @ W1_ + b1_)
        logits = h @ W2_ + b2_

        Ytr_names_one_hot = nn.functional.one_hot(Ytr[j], num_classes=len(vocab_alien_lang)+1).float()
        print(logits.shape)
        print(Ytr_names_one_hot.shape)
        loss = nn.functional.cross_entropy(logits, Ytr_names_one_hot.view(-1, len(vocab_alien_lang)+1))

        for p in parameters:
            p.grad = None
        loss.backward()

        for p in parameters:
            p.data += -0.01 * p.grad
    print(loss.item())
        

Epoch  0  has started
torch.Size([1, 18])
torch.Size([21])


RuntimeError: 0D or 1D target tensor expected, multi-target not supported